config/routes.rb
Rails.application.routes.draw do

  resources :users do
    put :join_team, on: :member
     delete :leave_team, on: :member
 end


  resources :comments
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :thedeadlines
  resources :tasks do
    resources :comments
  end
  resources :projects
  root 'teams#index'
  resources :teams
  
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/thedeadline.rb
class Thedeadline < ApplicationRecord
  validates :deadlinetime, presence: true
  has_many :tasks
end

app/controllers/thedeadlines_controller.rb
class ThedeadlinesController < ApplicationController
  before_action :set_thedeadline, only: %i[ show edit update destroy ]

  # GET /thedeadlines or /thedeadlines.json
  def index
    @thedeadlines = Thedeadline.all
  end

  # GET /thedeadlines/1 or /thedeadlines/1.json
  def show
  end

  # GET /thedeadlines/new
  def new
    @thedeadline = Thedeadline.new
  end

  # GET /thedeadlines/1/edit
  def edit
  end

  # POST /thedeadlines or /thedeadlines.json
  def create
    @thedeadline = Thedeadline.new(thedeadline_params)

    respond_to do |format|
      if @thedeadline.save
        format.html { redirect_to thedeadline_url(@thedeadline), notice: "Thedeadline was successfully created." }
        format.json { render :show, status: :created, location: @thedeadline }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @thedeadline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /thedeadlines/1 or /thedeadlines/1.json
  def update
    respond_to do |format|
      if @thedeadline.update(thedeadline_params)
        format.html { redirect_to thedeadline_url(@thedeadline), notice: "Thedeadline was successfully updated." }
        format.json { render :show, status: :ok, location: @thedeadline }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @thedeadline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /thedeadlines/1 or /thedeadlines/1.json
  def destroy
    @thedeadline.destroy

    respond_to do |format|
      format.html { redirect_to thedeadlines_url, notice: "Thedeadline was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_thedeadline
      @thedeadline = Thedeadline.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def thedeadline_params
      params.require(:thedeadline).permit(:deadlinetime)
    end
end

app/helpers/thedeadlines_helper.rb
module ThedeadlinesHelper
end

app/views/thedeadlines/_form.html.erb
<%= form_with(model: thedeadline) do |form| %>
  <% if thedeadline.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(thedeadline.errors.count, "error") %> prohibited this thedeadline from being saved:</h2>

      <ul>
        <% thedeadline.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :deadlinetime, style: "display: block" %>
    <%= form.datetime_field :deadlinetime %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/thedeadlines/_thedeadline.html.erb
<div id="<%= dom_id thedeadline %>">
  <p>
    <strong>Deadlinetime:</strong>
    <%= thedeadline.deadlinetime %>
  </p>

</div>

app/views/thedeadlines/edit.html.erb
<h1>Editing thedeadline</h1>

<%= render "form", thedeadline: @thedeadline %>

<br>

<div>
  <%= link_to "Show this thedeadline", @thedeadline %> |

</div>
  <%= link_to "Back to thedeadlines", deadlines_path,class: 'btn'%>
<%= render "common/footer" %>

app/views/thedeadlines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Thedeadlines</h1>

<div id="thedeadlines">
  <% @thedeadlines.each do |thedeadline| %>
    <%= render thedeadline %>
    <p>
      <%= link_to "Show this thedeadline", thedeadline %>
    </p>
  <% end %>
</div>
<% if current_user && current_user.admin? %>
<%= link_to "New thedeadline", new_thedeadline_path,class: 'btn'%>

<% end %>
  <%= link_to "Back to thedeadlines", thedeadlines_path,class: 'btn'%>
<%= render "common/footer" %>

app/views/thedeadlines/new.html.erb
<h1>New thedeadline</h1>

<%= render "form", thedeadline: @thedeadline %>

<br>


  <%= link_to "Back to thedeadlines", thedeadlines_path,class: 'btn'%>
<%= render "common/footer" %>

app/views/thedeadlines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @thedeadline %>
<% if current_user && current_user.admin? %>
<div>
  <%= link_to "Edit this thedeadline", edit_thedeadline_path(@thedeadline) %> |


  <%= button_to "Destroy this thedeadline", @thedeadline, method: :delete %>
</div>
<% end %>
  <%= link_to "Back to thedeadlines", thedeadlines_path,class: 'btn'%>