config/routes.rb
Rails.application.routes.draw do

  resources :users do
    put :join_team, on: :member
     delete :leave_team, on: :member
 end


  resources :comments
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :thedeadlines
  resources :tasks do
    resources :comments
  end
  resources :projects
  root 'teams#index'
  resources :teams
  
get '/login', to: 'sessions#new'
post '/login', to: 'sessions#create'
delete '/logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/task.rb
class Task < ApplicationRecord
  validates :task_title, presence: true
  has_many :comments
  belongs_to :project
   belongs_to :thedeadline,optional: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task_title, :task_description,:project_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
   <%= form.label :project_id %>
    <%= form.select :project_id, Project.all.map{ |c| [c.title, c.id] }, {}, :class => "form-control" %>
  </div>


  <div>
    <%= form.label :task_title, style: "display: block" %>
    <%= form.text_field :task_title %>
  </div>

  <div>
    <%= form.label :task_description, style: "display: block" %>
    <%= form.text_area :task_description %>
  </div>

  <div class="form-group">
   <%= form.label :thedeadline_id %>
    <%= form.select :thedeadline_id, Thedeadline.all.map{ |c| [c.deadlinetime, c.id] }, {}, :class => "form-control" %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<table id="<%= dom_id(task) %>" class="task-table">
  <tr>
    <th>Task title:</th>
    <td><%= task.task_title %></td>
  </tr>
  <tr>
    <th>Task description:</th>
    <td><%= task.task_description %></td>
  </tr>
</table>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%= link_to "Back to tasks", tasks_path %>
</div>
<%= render "common/footer" %>

app/views/tasks/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tasks</h1>

<div id="tasks">
  <% @tasks.each do |task| %>
    <%= render task %>
    <p>
      <%= link_to "Show this task", task %>
    </p>
  <% end %>
</div>
<% if current_user && current_user.admin? %>
<%= link_to "New task", new_task_path %><% end %>
<%= render "common/footer" %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Back to tasks", tasks_path %>
</div>
<%= render "common/footer" %>

app/views/tasks/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @task %>

<h2>comments</h2><hr>
<!-- 显示已有的评论 -->
<% @task.comments.each do |comment| %>
  <p><strong><%= comment.user.username %></strong>: <%= comment.content %></p>
<% end %>

<hr>


<!-- 跳转到评论页面 -->
<div class="text-center">
  <%= link_to("let comments", new_task_comment_path(@task), :style => "font-size: 30px; text-decoration:underline;") %>
</div>

<% if current_user && current_user.admin? %>

<div>
  <%= link_to "Edit this task", edit_task_path(@task) %> |
  <%= link_to "Back to tasks", tasks_path %>

  <%= button_to "Destroy this task", @task, method: :delete %>
</div>
<% end %>
<%= render "common/footer" %>